#!/bin/sh

echo "running pre-commit"

RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo git diff --cached --name-only --diff-filter=ACM "*.cs"

LC_ALL=C
# Select files to format
MANAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM "*.cs" | sed 's| |\\ |g')

echo "$MANAGED_FILES"

exec 1>&2

if [ -n "$MANAGED_FILES" ]; then

    echo -e "${YELLOW}Running pre-commit hook, dotnet format...${NC}"
	
    # Format all selected files
    echo "$MANAGED_FILES" | cat | xargs | sed -e 's/ /,/g' | dotnet format Lueben.Microservice.sln --no-restore --verbosity detailed --include -
	
    rc=$?

    if [[ $rc != 0 ]] ; then
       echo -e "${RED}Failed to format project, please fix this and commit again${NC}"
       exit $rc
    fi

    # Add back the modified files to staging
    echo "$MANAGED_FILES" | xargs git add
fi

exit 0